In [1]:
[1,2,3,4]*2

[1, 2, 3, 4, 1, 2, 3, 4]

## Numerical Python (Numpy)

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
a*2

array([2, 4, 6, 8])

In [5]:
a*3

array([ 3,  6,  9, 12])

In [7]:
b = a*4
b

array([ 4,  8, 12, 16])

## Math Function

In [8]:
np.sum(a)

10

In [10]:
np.mean(a)

2.5

In [11]:
np.std(a)

1.118033988749895

In [12]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [14]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [16]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])