# Numpy

NumPy (Numerical Python) adalah library Python yang fokus pada scientific computing. Numpy menyediakan fungsi yang siap pakai untuk memudahkan melakukan perhitungan saintifik seperti matriks, aljabar, statistik, dan sebagainya

In [1]:
#Import library
import numpy as np

In [2]:
#Membuat Array
C = np.array([50, 60, 70, 80, 90])
C

array([50, 60, 70, 80, 90])

In [3]:
#Operasi pada array
C*2

array([100, 120, 140, 160, 180])

In [4]:
C+10

array([ 60,  70,  80,  90, 100])

In [5]:
C-10

array([40, 50, 60, 70, 80])

In [7]:
C/2

array([25., 30., 35., 40., 45.])

In [8]:
contoh = C*5
contoh

array([250, 300, 350, 400, 450])

## Match Function

In [9]:
#Summary
total = np.sum(C)
total

350

In [11]:
#Mean
rata_rata = np.mean(C)
rata_rata

70.0

In [14]:
#Median
nilai_tengah = np.median(C)
nilai_tengah

70.0

In [16]:
#Nilai Maksimum
maks = np.max(C)
maks

90

In [17]:
#Nilai Minimum
mini = np.min(C)
mini

50

In [18]:
#Standard Deviasi
Sd = np.std(C)
Sd

14.142135623730951

# Pandas

Pandas adalah library open source yang ada pada bahasa pemrograman Python yang sering digunakan untuk memproses data, mulai pembersihan data, manipulasi data, hingga melakukan analisis data. 

In [19]:
#Import Library
import pandas as pd

In [20]:
umur = {'Kelas a':[19,20,19], 'kelas b':[18,19,21], 'Kelas c':[21,19,20]}
umur

{'Kelas a': [19, 20, 19], 'kelas b': [18, 19, 21], 'Kelas c': [21, 19, 20]}

In [21]:
#Membuat Data Frame
pd.DataFrame(umur)

Kelas a  kelas b  Kelas c
0       19       18       21
1       20       19       19
2       19       21       20

## Membaca File

In [22]:
#Import Data
ce = pd.read_csv('Data/cereal.csv')
ce

name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
1           100% Natural Bran   Q    C       120        3    5      15    2.0   
2                    All-Bran   K    C        70        4    1     260    9.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4              Almond Delight   R    C       110        2    2     200    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2    1     250    0.0   
73                       Trix   G    C       110        1    1     140    0.0   
74                 Wheat Chex   R    C       100        3    1     230    3.0   
75                   Wheaties   G    C       100        3    1     200    3.0   
76        Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass vitamins  shelf  weight  cups     rating  
0     5.0     6.0   280.0   FDA_25      3     1.0  0.33  68.402973  
1     8.0     8.0   135.0    FDA_0      3     1.0  1.00  33.983679  
2     7.0     5.0   320.0   FDA_25      3     1.0  0.33  59.425505  
3     8.0     0.0   330.0   FDA_25      3     1.0  0.50  93.704912  
4    14.0     8.0     NaN   FDA_25      3     1.0  0.75  34.384843  
..    ...     ...     ...      ...    ...     ...   ...        ...  
72   21.0     3.0    60.0   FDA_25      3     1.0  0.75  39.106174  
73   13.0    12.0    25.0   FDA_25      2     1.0  1.00  27.753301  
74   17.0     3.0   115.0   FDA_25      1     1.0  0.67  49.787445  
75   17.0     3.0   110.0   FDA_25      1     1.0  1.00  51.592193  
76   16.0     8.0    60.0   FDA_25      1     1.0  0.75  36.187559  

[77 rows x 16 columns]

In [23]:
#Melihat data teratas
ce.head() 

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass vitamins  shelf  weight  cups     rating  
0    5.0     6.0   280.0   FDA_25      3     1.0  0.33  68.402973  
1    8.0     8.0   135.0    FDA_0      3     1.0  1.00  33.983679  
2    7.0     5.0   320.0   FDA_25      3     1.0  0.33  59.425505  
3    8.0     0.0   330.0   FDA_25      3     1.0  0.50  93.704912  
4   14.0     8.0     NaN   FDA_25      3     1.0  0.75  34.384843

In [24]:
#Melihat data terbawah
ce.tail()

name mfr type  calories  protein  fat  sodium  fiber  \
72              Triples   G    C       110        2    1     250    0.0   
73                 Trix   G    C       110        1    1     140    0.0   
74           Wheat Chex   R    C       100        3    1     230    3.0   
75             Wheaties   G    C       100        3    1     200    3.0   
76  Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass vitamins  shelf  weight  cups     rating  
72   21.0     3.0    60.0   FDA_25      3     1.0  0.75  39.106174  
73   13.0    12.0    25.0   FDA_25      2     1.0  1.00  27.753301  
74   17.0     3.0   115.0   FDA_25      1     1.0  0.67  49.787445  
75   17.0     3.0   110.0   FDA_25      1     1.0  1.00  51.592193  
76   16.0     8.0    60.0   FDA_25      1     1.0  0.75  36.187559

In [28]:
#Melihat Index
ce.columns

Index(['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber',
       'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups',
       'rating'],
      dtype='object')

In [29]:
#Melihat jumlah baris dan kolom
ce.shape

(77, 16)

In [30]:
#Melihat data teraras kolom tertentu
ce.calories.head()

0     70
1    120
2     70
3     50
4    110
Name: calories, dtype: int64

In [32]:
ce['calories'].head()

0     70
1    120
2     70
3     50
4    110
Name: calories, dtype: int64

In [43]:
ce[['name','calories','protein','carbo','sugars','rating']].head()

name  calories  protein  carbo  sugars     rating
0                  100% Bran        70        4    5.0     6.0  68.402973
1          100% Natural Bran       120        3    8.0     8.0  33.983679
2                   All-Bran        70        4    7.0     5.0  59.425505
3  All-Bran with Extra Fiber        50        4    8.0     0.0  93.704912
4             Almond Delight       110        2   14.0     8.0  34.384843

In [37]:
#Melihat info data
ce.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      77 non-null     object 
 1   mfr       77 non-null     object 
 2   type      77 non-null     object 
 3   calories  77 non-null     int64  
 4   protein   77 non-null     int64  
 5   fat       77 non-null     int64  
 6   sodium    77 non-null     int64  
 7   fiber     77 non-null     float64
 8   carbo     76 non-null     float64
 9   sugars    76 non-null     float64
 10  potass    75 non-null     float64
 11  vitamins  77 non-null     object 
 12  shelf     77 non-null     int64  
 13  weight    77 non-null     float64
 14  cups      77 non-null     float64
 15  rating    77 non-null     float64
dtypes: float64(7), int64(5), object(4)
memory usage: 9.8+ KB


In [39]:
ce.type.value_counts()

C    74
H     3
Name: type, dtype: int64

In [42]:
#Memanggil data dengan nilai tertentu
ce[ce.type=='H']

name mfr type  calories  protein  fat  sodium  fiber  \
20  Cream of Wheat (Quick)   N    H       100        3    0      80    1.0   
43                   Maypo   A    H       100        4    1       0    0.0   
57          Quaker Oatmeal   Q    H       100        5    2       0    2.7   

    carbo  sugars  potass vitamins  shelf  weight  cups     rating  
20   21.0     0.0     NaN    FDA_0      2     1.0  1.00  64.533816  
43   16.0     3.0    95.0   FDA_25      2     1.0  1.00  54.850917  
57    NaN     NaN   110.0    FDA_0      1     1.0  0.67  50.828392